name: news_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7


  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1


  


dev_dependencies:
  flutter_test:
    sdk: flutter
  

flutter:
  uses-material-design: true
  assets:
     - assets/images/

     
